export const offersData = [
  {
    id: 1,
    title: "Fresh & Healthy",
    subtitle: "25% OFF Veggie Bowls",
    type: "discount",
    searchTerm: "Healthy",
    image: "../images/plate-with-delicious-veggie-food.jpg",
  },
  {
    id: 2,
    title: "Free Delivery",
    subtitle: "on all Groceries",
    type: "delivery",
    searchTerm: "Groceries",
    image: "../images/Free_Delivery.png",
  },
  {
    id: 3,
    title: "Pharmacy Offers!",
    subtitle: "Up to 30% OFF",
    type: "discount",
    searchTerm: "Pharmacy",
    image: "../images/Pharmacy Offers!.png",
  },
  {
    id: 4,
    title: "Fast Delivery",
    subtitle: "Items in 25 Min",
    type: "delivery",
    searchTerm: "Fast",
    image: "../images/freeDeleivery.png",
  },
  {
    id: 5,
    title: "Summer Sale",
    subtitle: "30% OFF Drinks",
    type: "discount",
    searchTerm: "Drinks",
    image: "../images/banana-smoothie-served-red-lipstick.jpg",
  },
  {
    id: 6,
    title: "Local Spots",
    subtitle: "10% OFF Italian",
    type: "discount",
    searchTerm: "Italian",
    image: "../images/french-restaurant-south-france.jpg",
  },
];
export const restaurantsData = [
  {
    id: 1,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.5,
    deliveryTime: "30 - 45 min",
    deliveryFee: "Delivery $5",
    category: "Italian",
    hasDiscount: false,
    deliveryFeeValue: 5,
    deliveryTimeMin: 30,
    minPrice: 5,
    menu: [
      { id: 101, name: "Margherita Pizza", price: 12 },
      { id: 102, name: "Pepperoni Feast", price: 15 },
      { id: 103, name: "Garlic Bread", price: 5 },
    ],
  },
  {
    id: 2,
    name: "Pizza Place",
    isOpen: false,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Delivery $3",
    category: "Italian",
    hasDiscount: true,
    deliveryFeeValue: 3,
    deliveryTimeMin: 20,
    minPrice: 3,
    menu: [
      { id: 201, name: "Cheese Pizza", price: 10 },
      { id: 202, name: "Veggie Pizza", price: 13 },
      { id: 203, name: "Coke", price: 2 },
    ],
  },
  {
    id: 3,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Italian",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 10,
    menu: [
      { id: 301, name: "BBQ Chicken Pizza", price: 16 },
      { id: 302, name: "Pasta Alfredo", price: 14 },
      { id: 303, name: "Salad", price: 6 },
    ],
  },
  {
    id: 4,
    name: "The Burger House",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_2osdjt2osdjt2osd.png",
    rating: 4.7,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Burgers",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 2,
    menu: [
      { id: 401, name: "Classic Beef Burger", price: 8 },
      { id: 402, name: "Cheese Burger", price: 9 },
      { id: 403, name: "French Fries", price: 3 },
    ],
  },
  {
    id: 5,
    name: "Quick Pharmacy",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_xyrbr0xyrbr0xyrb.png",
    rating: 4.9,
    deliveryTime: "15 - 25 min",
    deliveryFee: "Delivery $3",
    category: "Pharmacy",
    hasDiscount: true,
    deliveryFeeValue: 3,
    deliveryTimeMin: 15,
    minPrice: 10,
    menu: [
      { id: 501, name: "Panadol Advance", price: 5 },
      { id: 502, name: "Vitamin C", price: 12 },
      { id: 503, name: "First Aid Kit", price: 25 },
    ],
  },
  {
    id: 6,
    name: "Global Groceries",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_jeorawjeorawjeor.png",
    rating: 4.2,
    deliveryTime: "40 - 50 min",
    deliveryFee: "Delivery $7",
    category: "Groceries",
    hasDiscount: false,
    deliveryFeeValue: 7,
    deliveryTimeMin: 40,
    minPrice: 10,
    menu: [
      { id: 601, name: "Milk (1L)", price: 2 },
      { id: 602, name: "Bread Bundle", price: 3 },
      { id: 603, name: "Eggs (12pcs)", price: 4 },
    ],
  },
  {
    id: 7,
    name: "Healthy Greens",
    isOpen: true,
    image: "../images/healthyGrean.png",
    rating: 4.8,
    deliveryTime: "25 - 35 min",
    deliveryFee: "Delivery $4",
    category: "Healthy",
    hasDiscount: true,
    deliveryFeeValue: 4,
    deliveryTimeMin: 25,
    minPrice: 6,
    menu: [
      { id: 701, name: "Quinoa Salad", price: 11 },
      { id: 702, name: "Green Smoothie", price: 7 },
      { id: 703, name: "Fruit Bowl", price: 8 },
    ],
  },
  {
    id: 8,
    name: "The Coffee Spot",
    isOpen: true,
    image: "../images/Screenshot 2025-12-07 193334.png",
    rating: 4.6,
    deliveryTime: "10 - 20 min",
    deliveryFee: "Delivery $2",
    category: "Drinks",
    hasDiscount: true,
    deliveryFeeValue: 2,
    deliveryTimeMin: 10,
    minPrice: 2,
    menu: [
      { id: 801, name: "Latte", price: 4 },
      { id: 802, name: "Cappuccino", price: 5 },
      { id: 803, name: "Croissant", price: 3 },
    ],
  },
  {
    id: 9,
    name: "Asian Delights",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_60mr2k60mr2k60mr.png",
    rating: 4.4,
    deliveryTime: "35 - 50 min",
    deliveryFee: "Delivery $6",
    category: "Asian",
    hasDiscount: false,
    deliveryFeeValue: 6,
    deliveryTimeMin: 35,
    minPrice: 7,
    menu: [
      { id: 901, name: "Sushi Set", price: 20 },
      { id: 902, name: "Ramen", price: 15 },
      { id: 903, name: "Spring Rolls", price: 6 },
    ],
  },
  {
    id: 10,
    name: "Fresh Bakery",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_fwdt20fwdt20fwdt.png",
    rating: 4.9,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Delivery $3",
    category: "Desserts",
    hasDiscount: false,
    deliveryFeeValue: 3,
    deliveryTimeMin: 20,
    minPrice: 4,
    menu: [
      { id: 1001, name: "Chocolate Cake", price: 5 },
      { id: 1002, name: "Blueberry Muffin", price: 3 },
      { id: 1003, name: "Donut Box", price: 12 },
    ],
  },
  {
    id: 11,
    name: "The Coffee Spot",
    isOpen: true,
    image: "../images/Screenshot 2025-12-07 193334.png",
    rating: 4.6,
    deliveryTime: "10 - 20 min",
    deliveryFee: "Delivery $2",
    category: "Drinks",
    hasDiscount: false,
    deliveryFeeValue: 2,
    deliveryTimeMin: 10,
    minPrice: 2,
    menu: [
      { id: 1101, name: "Espresso", price: 3 },
      { id: 1102, name: "Mocha", price: 5 },
      { id: 1103, name: "Cookie", price: 2 },
    ],
  },
  {
    id: 12,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Italian",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 10,
    menu: [
      { id: 1201, name: "Meat Lovers Pizza", price: 18 },
      { id: 1202, name: "Lasagna", price: 15 },
      { id: 1203, name: "Tiramisu", price: 7 },
    ],
  },
  {
    id: 13,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Italian",
    hasDiscount: true,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 10,
    menu: [
      { id: 1301, name: "Hawaii Pizza", price: 14 },
      { id: 1302, name: "Pasta Carbonara", price: 13 },
      { id: 1303, name: "Garlic Knot", price: 4 },
    ],
  },
  {
    id: 14,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Italian",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 10,
    menu: [
      { id: 1401, name: "Buffalo Pizza", price: 16 },
      { id: 1402, name: "Fries", price: 3 },
      { id: 1403, name: "Juice", price: 3 },
    ],
  },
  {
    id: 15,
    name: "Healthy Greens",
    isOpen: true,
    image: "../images/healthyGrean.png",
    rating: 4.8,
    deliveryTime: "25 - 35 min",
    deliveryFee: "Free Delivery",
    category: "Healthy",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 25,
    minPrice: 6,
    menu: [
      { id: 1501, name: "Avocado Toast", price: 9 },
      { id: 1502, name: "Kale Salad", price: 10 },
      { id: 1503, name: "Detox Water", price: 4 },
    ],
  },
  {
    id: 16,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Italian",
    hasDiscount: true,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 10,
    menu: [
      { id: 1601, name: "Greek Pizza", price: 15 },
      { id: 1602, name: "Bruschetta", price: 6 },
      { id: 1603, name: "Wine (Bottle)", price: 25 },
    ],
  },
  {
    id: 17,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Italian",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 10,
    menu: [
      { id: 1701, name: "Four Cheese Pizza", price: 17 },
      { id: 1702, name: "Spaghetti", price: 12 },
      { id: 1703, name: "Ice Cream", price: 5 },
    ],
  },
  {
    id: 18,
    name: "Global Groceries",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_jeorawjeorawjeor.png",
    rating: 4.2,
    deliveryTime: "40 - 50 min",
    deliveryFee: "Free Delivery",
    category: "Groceries",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 40,
    minPrice: 10,
    menu: [
      { id: 1801, name: "Rice (5kg)", price: 10 },
      { id: 1802, name: "Chicken Breast", price: 12 },
      { id: 1803, name: "Pasta Pack", price: 2 },
    ],
  },
  {
    id: 19,
    name: "Pizza Place",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_f83300f83300f833.png",
    rating: 4.3,
    deliveryTime: "20 - 30 min",
    deliveryFee: "Free Delivery",
    category: "Italian",
    hasDiscount: false,
    deliveryFeeValue: 0,
    deliveryTimeMin: 20,
    minPrice: 10,
    menu: [
      { id: 1901, name: "Ranch Pizza", price: 16 },
      { id: 1902, name: "Mozzarella Sticks", price: 7 },
      { id: 1903, name: "Soda", price: 2 },
    ],
  },
  {
    id: 20,
    name: "Quick Pharmacy",
    isOpen: true,
    image: "../images/Gemini_Generated_Image_xyrbr0xyrbr0xyrb.png",
    rating: 4.9,
    deliveryTime: "15 - 25 min",
    deliveryFee: "Delivery $3",
    category: "Pharmacy",
    hasDiscount: false,
    deliveryFeeValue: 3,
    deliveryTimeMin: 15,
    minPrice: 10,
    menu: [
      { id: 2001, name: "Omega 3", price: 15 },
      { id: 2002, name: "Baby Wipes", price: 6 },
      { id: 2003, name: "Hand Sanitizer", price: 3 },
    ],
  },
  {
    id: 21,
    name: "Pasta Bella",
    isOpen: true,
    image: "../images/Italiano.png",
    rating: 4.1,
    deliveryTime: "15 - 25 min",
    deliveryFee: "Delivery $7",
    category: "Italian",
    hasDiscount: true,
    deliveryFeeValue: 3,
    deliveryTimeMin: 15,
    minPrice: 10,
    menu: [
      { id: 2101, name: "Pesto Pasta", price: 14 },
      { id: 2102, name: "Ravioli", price: 16 },
      { id: 2103, name: "Lemonade", price: 4 },
    ],
  },
];
